// <auto-generated />
namespace MySensei.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class fix31 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix31));
        
        string IMigrationMetadata.Id
        {
            get { return "201512081733151_fix31"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
